### PR TITLE
Generate interface implementation members

### PR DESCRIPTION
**Pull request by mcon**
# Summary
Able to generate placeholder implementations of interfaces for a particular class. The implementation does the bare bones, and is at present only able to handle the interface implementation being completely empty.

e.g.
```
type IPrintable =
   abstract member Print1 : unit -> unit
   abstract member Print2 : string -> unit
type SomeClass1(x: int, y: float) =
   interface IPrintable
```
to
```
type IPrintable =
   abstract member Print1 : unit -> unit
   abstract member Print2 : string -> unit
type SomeClass1(x: int, y: float) =
   interface IPrintable with
     member this.Print1 () = failwith "todo"
     member this.Print2 var0 = failwith "todo"
```

# TODO
 - [x] Insertion of the `with` keyword if it's missing from the `IInterfaceImplementation`
 - [x] More testing to add around FSharpElementFactory additions
 - [x] Testing of generics
 - [x] Expansion of tupled members
 - [ ] Make action a quickfix

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I recommend to look at https://github.com/fsprojects/Archive-VisualFSharpPowerTools/blob/master/src/FSharp.Editing/CodeGeneration/InterfaceStubGenerator.fs for ideas etc.

**Comment by auduchinok** [comment]
Please make it a quick fix instead of a context action. Here's an example QF working on the same errors you're after: https://github.com/JetBrains/fsharp-support/commit/b28b01df5f59bd9e2c4900bc130aeb71bbf84086.

**Comment by mcon** [comment]
Hi @auduchinok, this one's pretty much good to go, but can't get the quick fix for an `IInterfaceImplementation` to be recognized - any ideas why that might be?

**Comment by dbarbashov** [comment]
Great feature! Any progress on this?

**Comment by mcon** [comment]
Hi @auduchinok,

I've merged in `net202`, and worked around the changes in member grammar - looks to me like a small tweak was required to the parameters, and I've added a parser testcase for that too.

Taking a look at making this one a quick fix, it seems that I'd be looking to match a parse error (https://github.com/fsharp/FSharp.Compiler.Service/blob/1d173b6e753199f4598f6283ff5ecac811cad18e/src/fsharp/FSStrings.resx#L486), which gets mapped to `SyntaxError` (https://github.com/fsharp/FSharp.Compiler.Service/blob/9.0.0/src/fsharp/CompileOps.fs#L258), which would then get triggered for every syntax error in a file - I could update the PR to work that way, but I don't know what would be best for performance. If you could let me know I'll update it however you'd like.

Cheers,
Matt

**Comment by auduchinok** [comment]
Hi @mcon,

I'm sorry for the late response here. I've merged in `net203`, made it a quick fix instead of a context action (or an intention, in IntelliJ terms), and did some cleanup.

> and worked around the changes in member grammar - looks to me like a small tweak was required to the parameters, and I've added a parser testcase for that too.

It was almost correct: there actually may be no parameters pattern, and that would mean the member declaration is a property declaration.

> Taking a look at making this one a quick fix, it seems that I'd be looking to match a parse error 

Yes, if there's a `with` keyword but no actual members, it fails to parse the interface implementation. It should be better handled in the FCS parser by adding some error recovery, so we could use the interface implementation node here. The quick fix works the same way it was as an intention: only when there's no `with` keyword or if there're any members.

What's needed to be done here (I'll add more if anything comes to my mind):

* handle method overloads (check signatures instead of member names)
* print types where needed for overloads (including for already implemented members)

**Comment by auduchinok** [comment]
I've implemented things needed for what it seems the most common cases (the todo list has became quite long here) and am going to handle the missing parts out of scope of this PR.

**Comment by auduchinok** [comment]
@mcon Thanks for your contribution here! It worked as a good starting point, and we're almost there now, it'll work great once remaining pieces are done.

**Pull request merged**
