### PR TITLE
Provide local symbols for for and match expressions

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

image

image

### CODE REVIEW

**Comment by auduchinok** [comment]
Linking [RIDER-16740](https://youtrack.jetbrains.com/issue/RIDER-16740).

**Comment by vasily-kirichenko** [comment]
I need https://github.com/Microsoft/visualfsharp/pull/5158 merged to provide values for SynApp arguments.

**Comment by saul** [comment]
Can this be merged now @auduchinok ?

**Comment by auduchinok** [comment]
@saul Thanks for pinging, I have somehow missed the moment @vasily-kirichenko's PR had been merged to VFT. I'll update our FCS soon and let him know.

**Comment by NinoFloris** [comment]
Is there any blocker on this?

**Comment by vasily-kirichenko** [comment]
I've merged 191 into this. Still works:

image

image

The last one still does not work

image

**Comment by auduchinok** [comment]
I've partially merged this PR before and all working examples are already in 191.
@vasily-kirichenko FCS changes you needed for the last case are also merged now, you're welcome to implement that last part. 🙂

**Comment by vasily-kirichenko** [comment]
The last part should work now automatically.

**Comment by auduchinok** [comment]
I'm not sure what's expected to be shown there, though.
This PR adds showing values next to declarations and `x`, `y`, `z` values aren't being declared in that expression/statement.

Showing values next to their usages in some cases was added separately in https://github.com/JetBrains/fsharp-support/commit/cef3cd723aa7960708917be195da19425de2e33c and it works after you step to next statement after one with usages. Is this what you expect here?
Screenshot 2019-03-29 at 12 19 50

**Comment by vasily-kirichenko** [comment]
Try multiline.

**Comment by auduchinok** [comment]
What actually should it change?
Making it multi line won't add declaration tree nodes nor will it split this statement into several ones to show symbol usages next to them.

**Pull request closed without merging**
