### PR TITLE
Migrate to new SDK.

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by nojaf** [comment]
Out of curiosity, is this the .NET Core SDK?

**Comment by auduchinok** [comment]
@nojaf It's a temporary name for unified R#/Rider SDK which is needed for our internal CI.

**Comment by NinoFloris** [comment]
How would we be able to run this?

**Comment by auduchinok** [comment]
@NinoFloris Building and running the plugin should work exactly the same way as it is now, and we're evaluating that the change doesn't break anything for non-CI scenarios.

**Comment by nojaf** [comment]
@auduchinok I saw a tweet from @kskrygan mentioning that that Rider backend services would run completely on .NET Core in 2020.1 and I was wondering if this SDK was he mentioned.

**Comment by auduchinok** [comment]
@nojaf Ah, I see. No, it's not related to the runtime migration, just changes of how our SDK is constructed and referenced in the bundled plugins.

**Pull request merged**
